# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oQhC5qR0OccMHQDD2EaaxpHZAaU4yWjg
"""

#1
weight=float(input("Enter the weight : "))
height=float(input("Enter the height : "))
area_of_triangle=float((weight*height)/2)
print(" Area of the triangle : {}".format(area_of_triangle))

#2
weight=float(input("Enter the weight in kg : "))
height=float(input("Enter the height  in meters : "))
BMI=round(weight/(height**2),2)
print(" Body Mass Index is {}".format(BMI))

#3
students={}
name=input("Enter the name of the student : ")
score=int(input("Enter the score of the student : "))
students[name]=score
print(students)

#4
age=int(input("Enter age : "))
if 0<age<=18:
  print("Minor")
elif age<40:
  print("Adult")
else:
  print("Senior")

#5
for i in range(1,50):
  if(i%2==0):
    print(i,end=' ')

#6
password='abcde'
choice=1
while choice>0:
  user_pass=input("Enter Password: ")
  if(user_pass.lower()==password):
    print("Password matched ...")
    choice=0
  else:
    print("Enter again...")
    choice=1

#7
def average(lis):
  total=0
  for i in lis:
    total+=i
  avg=total/len(lis)
  print("Average of given list : {}".format(avg))

average([2,3,4,1])

#8
def countVowels(string):
  vowels=['a','e','i','o','u']
  count=0
  for i in string:
    if i in vowels:
      count+=1
  print("Vowels count is a string  is  {}".format(count))

countVowels("asdfgivo")

#9
from datetime import *

today = date.today()
print("Today's date:", today)
current_time =datetime.now()

print(" current Time now  is:", current_time)

#10
def addition(a,b):
    try:
      ans =a+b
      print("Addition of numbers is : {}".format(ans))
    except TypeError as error:
      print("Don't Enter different Datatype please enter numbers")

addition(1,2)

#11
try:
  x = int(input("Please enter a number: "))
except ValueError:
  print("Oops!  That was not a valid number.  Try again...")

#12
def division(a,b):

  try:
    ans=a/b
    print("Ans : {}".format(ans))
  except ZeroDivisionError as error:
    print("Error : {} is not possible ".format(error))


division(5,2)

#13
from google.colab import drive
drive.mount('/content/drive')
with open("/content/drive/MyDrive/sample_for_internal.txt",'w') as file:
  file.write("Hello, Python!")
  file.close()

#14
with open('/content/drive/MyDrive/sample_for_internal.txt','r')as file:
  data=file.read()
  print(data)
  file.close()

#15
with open("/content/drive/MyDrive/sample_for_internal.txt",'a') as file:
  file.write("\n Good Evening")

with open('/content/drive/MyDrive/sample_for_internal.txt','r')as file:
  data=file.read()
  print(data)
  file.close()